### PR TITLE
Add 'requirements.txt' file

### PR DESCRIPTION
**Pull request by vkarak**
Since I've seen that this was missing.

### CODE REVIEW

**Review by tgamblin — APPROVED** [review]

**Comment by tgamblin** [comment]
@alalazo: I am not sure what the conventions are, but do we need this to be represented in two places?  We already put this in `pyproject.toml`: https://github.com/archspec/archspec/blob/master/pyproject.toml#L27

**Comment by alalazo** [comment]
I don't think we need this if we use `pyproject.toml`

**Comment by alalazo** [comment]
Let me double check conventions and post here some reference.

**Review by alalazo — CHANGES_REQUESTED** [review]
Just double checked [poetry docs](https://python-poetry.org/docs/pyproject/) and we don't need this file for compatibility with other tools, since the source distribution on PyPI contains a `setup.py` generated by `poetry` where these requirements are already present.

Why are you adding this? Did you see any warning?

**Comment by vkarak** [comment]
Hmm, ok, I went on traditionally. I need to try with poetry. I haven't done that before and since I wanted to try archspec quickly, I found it easier to have the requirements to set it up. Since I wanted to use it as a "user" for the moment, I thought the poetry was only relevant for "developers" according to the documentation, so I kind of skipped this part :-) When I tried to `pip install` it, it was missing the `archspec-json`, so I thought, I will go through the repo and install the requirements manually in a virtual env the "classical" way.

**Comment by alalazo** [comment]
> When I tried to pip install it, it was missing the archspec-json, so I thought, I will go through the repo and install the requirements manually in a virtual env the "classical" way.

Hmm, what did you try to pip install? A checkout of the repository? The source distribution on PyPI should have the json database in the tar file.

**Comment by tgamblin** [comment]
If you just want to try it as a user, `pip3 install archspec` -- will that work?

**Comment by alalazo** [comment]
```
culpo@MacBook-Pro tmp % python3 -m venv py3
culpo@MacBook-Pro tmp % . py3/bin/activate

(py3) culpo@MacBook-Pro tmp % pip install archspec
Collecting archspec
  Downloading https://files.pythonhosted.org/packages/ca/00/4dd64879829606b2a7136daf014c5952a4aeadaee74cc0f366552b6cf886/archspec-0.1.2-py2.py3-none-any.whl (40kB)
     |████████████████████████████████| 40kB 991kB/s 
Collecting six<2.0.0,>=1.13.0 (from archspec)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting click<8.0,>=7.1.2 (from archspec)
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
Installing collected packages: six, click, archspec
Successfully installed archspec-0.1.2 click-7.1.2 six-1.15.0

(py3) culpo@MacBook-Pro tmp % archspec --help
Usage: archspec [OPTIONS] COMMAND [ARGS]...

  archspec command line interface

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  cpu  archspec command line interface for CPU
(py3) culpo@MacBook-Pro tmp % archspec cpu   
cannonlake
```

**Comment by vkarak** [comment]
Hmm, I must have messed something before, because I tried a clean install and it works. I think I tried to pip install it in a virtual env from within the cloned repo and that perhaps got it confused. I need to check my history. But you can close this.

**Comment by vkarak** [comment]
```pycon
>>> import archspec
>>> import archspec.cpu
>>> import archspec.cpu.TARGETS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'archspec.cpu.TARGETS'
>>> archspec.cpu.TARGETS
<archspec.cpu.schema.LazyDictionary object at 0x10f5738e0>
>>> list(archspec.cpu.TARGETS.keys())
['x86', 'i686', 'pentium2', 'pentium3', 'pentium4', 'prescott', 'x86_64', 'nocona', 'core2', 'nehalem', 'westmere', 'sandybridge', 'ivybridge', 'haswell', 'broadwell', 'skylake', 'mic_knl', 'skylake_avx512', 'cannonlake', 'cascadelake', 'icelake', 'k10', 'bulldozer', 'piledriver', 'steamroller', 'excavator', 'zen', 'zen2', 'ppc64', 'power7', 'power8', 'power9', 'ppc64le', 'power8le', 'power9le', 'aarch64', 'thunderx2', 'a64fx', 'graviton', 'graviton2', 'arm', 'ppc', 'ppcle', 'sparc', 'sparc64']
```

This was complaining for some reason before.

**Comment by vkarak** [comment]
I can't reproduce it now, so I don't know what was wrong. All good!

**Pull request closed without merging**
