### PR TITLE
Add Code QL analysis to the CI workflow

### PR DESCRIPTION
**Pull request by alalazo**

### CODE REVIEW

**Comment by alalazo** [comment]
@tgamblin Here we got only five "Notes". Four of them were "false positives" triggered by the way we wrote some tests to be generic. One was minor but legitimate, and it has been fixed automatically with the last commit. See [here](https://github.com/archspec/archspec/security/code-scanning?query=ref%3Arefs%2Fpull%2F57%2Fmerge+tool%3ACodeQL+is%3Aclosed)

**Review by ArangoGutierrez — CHANGES_REQUESTED** [review]
Could you squash the commits into one, and give the PR a description :) 
so far looks good, thanks!

**Comment by alalazo** [comment]
@ArangoGutierrez The commit can be squashed on merge, not sure what I should add besides the title:

"Add Code QL analysis on the CI workflow"

This PR is really adding some static analysis to the codebase.

**Review by ArangoGutierrez — APPROVED** [review]
👍🏽

**Review by boegel — APPROVED** [review]

**Pull request merged**
