### PR TITLE
Add support for CPU detection on Windows

### LINKED ISSUE #113: Imprecise information returned from archspec.cpu.host() on Windows
On windows, archspec could return more significant info. It seems to provide default information that isn't detailed for the current system. My understanding is that there should be similar outputs for windows and WSL2 since they are on the same physical machine.

I ran this code through spack to test.

```
 >>> spack python
 >>> import archspec
 >>> archspec.cpu.host()
Microarchitecture('AMD64', [], 'generic', [], {}, 0)
```

On WSL2 for the same machine, `archspec.cpu.host()` returns much more significant info. 
```
 >>> bin/spack python
 >>> import archspec
 >>> archspec.cpu.host().family
Microarchitecture('x86_64', [], 'generic', set(), {'gcc': [{'versions': '4.2.0:', 'name': 'x86-64', 'flags': '-march={name} -mtune=generic'}, {'versions': ':4.1.2', 'name': 'x86-64', 'flags': '-march={name} -mtune={name}'}], 'apple-clang': [{'versions': ':', 'name': 'x86-64', 'flags': '-march={name}'}], 'clang': [{'versions': ':', 'name': 'x86-64', 'flags': '-march={name} -mtune=generic'}], 'aocc': [{'versions': '2.2:', 'name': 'x86-64', 'flags': '-march={name} -mtune=generic'}], 'intel': [{'versions': ':', 'name': 'pentium4', 'flags': '-march={name} -mtune=generic'}], 'oneapi': [{'versions': ':', 'name': 'x86-64', 'flags': '-march={name} -mtune=generic'}], 'dpcpp': [{'versions': ':', 'name': 'x86-64', 'flags': '-march={name} -mtune=generic'}], 'nvhpc': []}, 0)
```
For brevity, I showed the `archspec.cpu.host().family` output instead

### PR DESCRIPTION
**Pull request by alalazo**
requires #149 
closes #129
closes #114
closes #113

This PR builds on #129 and #149 to add support for Windows. Features detection is done using `cpuid`. The `cpuid` calls that we need to detect features are in https://github.com/archspec/archspec-json/pull/86. We also forked [archspec/cpuid](https://github.com/archspec/cpuid) and use it here as a submodule.

Modifications:
- [x] Add a new method to detect CPU features and vendor using `cpuid`
- [x] Add unit tests for the new method, including Windows

### CODE REVIEW

**Comment by alalazo** [comment]
@isuruf As of now I just tried the `cpuid` method on `linux` manually. I'll try to test drive this PR on Windows tomorrow. Can you check it out too and see if it behaves correctly? Also, feel free to comment on/review the PR. Thanks for all the work done so far to push Windows support! :slightly_smiling_face:

**Comment by alalazo** [comment]
Also @johnwparent and @scheibelp might be interested

**Comment by isuruf** [comment]
> We also forked [archspec/cpuid](https://github.com/archspec/cpuid) and use it here as a submodule.

Great. My fork at https://github.com/isuruf/cpuid.py/commit/48c045ce718ecc8ca306cfea7c67d7164b7fd3c1 has a commit that adds macosx support as well. Not necessary though.

> Can you check it out too and see if it behaves correctly?

Will do that in a week when I get access to the windows machine again.

**Comment by alalazo** [comment]
I need to double check if we have some flags with slightly different names :slightly_smiling_face: Anyhow, on a quite old Windows laptop:
Screenshot from 2024-02-16 09-57-05

**Comment by alalazo** [comment]
Detection is fixed:
Screenshot from 2024-02-16 11-10-15

**Review by tgamblin — COMMENTED** [review]
LGTM!  Thanks for getting this in @alalazo

**Review by tgamblin — APPROVED** [review]

**Comment by isuruf** [comment]
Thanks @alalazo for the support.

**Pull request merged**
