### PR TITLE
add methods to return known families, vendors and features

### PR DESCRIPTION
**Pull request by migueldiascosta**
Hi,
is there already a way of getting these?

If not, is this a good way?

### CODE REVIEW

**Comment by migueldiascosta** [comment]
probably for a separate PR, but to give a use case:

```python
def _get_virtual_microarchitecture(family, min_feature, vendors):
    """Returns a maximum set of features compatible with a minumum feature
    across a list of vendors of the same family and a list of microarchitectures
    compatible with that set of features.
    """

    if family not in _known_families():
        msg = "Unknown family {0}"
        raise ValueError(msg.format(family))

    if min_feature not in _known_features()[family]:
        msg = "Unknown feature {0}"
        raise ValueError(msg.format(min_feature))

    if not all(vendor in _known_vendors()[family] for vendor in vendors):
        msg = "Not all vendors in {0} are known in family {1})"
        raise ValueError(msg.format(vendors, family))

    virtual_microarchitecture = set()
    compatible_microarchitectures = []
    for arch in _known_microarchitectures().values():
        if arch.family == family:
            if any(vendor == arch.vendor for vendor in vendors):
                if min_feature in arch.features:
                    compatible_microarchitectures.append(arch.name)
                    if len(virtual_microarchitecture) == 0:
                        virtual_microarchitecture.update(arch.features)
                    else:
                        virtual_microarchitecture = virtual_microarchitecture.intersection(arch.features)

    # TODO: define a VirtualMicroarchitecture object?
    return virtual_microarchitecture, compatible_microarchitectures
```

which can be used for something like

```bash
python -c "import archspec.cpu; print(archspec.cpu.microarchitecture._get_virtual_microarchitecture('x86_64', 'avx', ['AuthenticAMD', 'GenuineIntel']))"
(set([u'aes', u'avx', u'mmx', u'sse4_1', u'sse2', u'pclmulqdq', u'ssse3', u'sse', u'sse4_2']), [u'bulldozer', u'icelake', u'zen', u'skylake', u'excavator', u'haswell', u'broadwell', u'cascadelake', u'skylake_avx512', u'cannonlake', u'steamroller', u'ivybridge', u'piledriver', u'mic_knl', u'zen2', u'sandybridge'])
```

the motivation being, once compilers and flags are added, building minimally generic but sufficiently performant binaries for `family/virtual_microarchitecture`... (?)

**Comment by alalazo** [comment]
> once compilers and flags are added, building minimally generic but sufficiently performant binaries

We have in the roadmap the addition of virtual microarchitectures, but instead of adding nodes to the microarchitecture DAG on the fly - which would require a fine knowledge of compiler flags, would be dynamic and not part of the JSON, would not be standard - we want to pull in the JSON file something like the x86_64 levels that are being discussed in the glibc community or the ARM vX.Y levels.

**Comment by migueldiascosta** [comment]
@alalazo I suppose you're right w.r.t. defining the complete virtual microarchitecture. 

Still, having a way of dynamically generating this type of set of instructions and compatible microarchitectures could be useful? Anyway, it was just a use case :)

**Comment by migueldiascosta** [comment]
e.g. something like

```bash
python3 -c "import pprint; pp = pprint.PrettyPrinter(indent=1, depth=3, width=400, compact=True); import archspec.cpu; pp.pprint(archspec.cpu.microarchitecture._get_compatible_features('x86_64', ['avx2'], ['AuthenticAMD', 'GenuineIntel']))"
{'compatible_features': ['aes', 'avx', 'avx2', 'bmi1', 'bmi2', 'f16c', 'fma', 'mmx', 'movbe', 'pclmulqdq', 'sse', 'sse2', 'sse4_1', 'sse4_2', 'ssse3'],
 'compatible_microarchitectures': ['broadwell', 'cannonlake', 'cascadelake', 'excavator', 'haswell', 'icelake', 'mic_knl', 'skylake', 'skylake_avx512', 'zen', 'zen2'],
 'incompatible_features': {'broadwell': ['adx', 'popcnt', 'rdrand', 'rdseed'],
                           'cannonlake': ['adx', 'avx512bw', 'avx512cd', 'avx512dq', 'avx512f', 'avx512ifma', 'avx512vbmi', 'avx512vl', 'clflushopt', 'popcnt', 'rdrand', 'rdseed', 'sha', 'umip', 'xsavec', 'xsaveopt'],
                           'cascadelake': ['adx', 'avx512_vnni', 'avx512bw', 'avx512cd', 'avx512dq', 'avx512f', 'avx512vl', 'clflushopt', 'clwb', 'popcnt', 'rdrand', 'rdseed', 'xsavec', 'xsaveopt'],
                           'excavator': ['abm', 'cx16', 'fma4', 'fsgsbase', 'sse4a', 'tbm', 'xop'],
                           'haswell': ['popcnt', 'rdrand'],
                           'icelake': ['adx', 'avx512_bitalg', 'avx512_vbmi2', 'avx512_vnni', 'avx512_vpopcntdq', 'avx512bw', 'avx512cd', 'avx512dq', 'avx512f', 'avx512ifma', 'avx512vbmi', 'avx512vl', 'clflushopt', 'clwb', 'gfni', 'popcnt', 'rdpid', 'rdrand', 'rdseed', 'sha_ni', 'umip', 'vaes', 'vpclmulqdq', 'xsavec', 'xsaveopt'],
                           'mic_knl': ['adx', 'avx512cd', 'avx512er', 'avx512f', 'avx512pf', 'popcnt', 'rdrand', 'rdseed'],
                           'skylake': ['adx', 'clflushopt', 'popcnt', 'rdrand', 'rdseed', 'xsavec', 'xsaveopt'],
                           'skylake_avx512': ['adx', 'avx512bw', 'avx512cd', 'avx512dq', 'avx512f', 'avx512vl', 'clflushopt', 'clwb', 'popcnt', 'rdrand', 'rdseed', 'xsavec', 'xsaveopt'],
                           'zen': ['abm', 'clflushopt', 'clzero', 'cx16', 'fsgsbase', 'popcnt', 'rdseed', 'sse4a', 'xsavec', 'xsaveopt'],
                           'zen2': ['abm', 'clflushopt', 'clwb', 'clzero', 'cx16', 'fsgsbase', 'popcnt', 'rdseed', 'sse4a', 'xsavec', 'xsaveopt']},
 'recommended_build_arch': {'incompatible_features': ['popcnt', 'rdrand'], 'name': 'haswell'}}
```

if you guys think this might make sense within archspec, I can open a separate PR (dependent on this one). But of course, anyone can implement this in their own scripts using archspec.

**Comment by alalazo** [comment]
@migueldiascosta Closing sa stale. Also we added the generic x86_64 and aarch64 levels in the latest releases

**Pull request closed without merging**
